### ISSUE TITLE
Desarrollar el endpoint POST /login para autenticar usuarios

### ISSUE THREAD

**Issue by gonzalorosofsky** [igrowker/i004-reffindr-back-nodejs#27]
Autentica a los usuarios (inquilinos o propietarios) y devuelve un token de sesión.

**Comment by CarlosDaniel661** [comment]
Por favor, detallar las acciones necesarias a validar para ajustar correctamente los test

**Comment by gonzalorosofsky** [comment]
const validateLogin: ValidationChain[] = [
  check('email').isEmail().withMessage('Debe ingresar un mail válido.'),

  check('password').notEmpty().withMessage('Debe ingresar una contraseña.'),
]

Se adjuntan las validaciones correspondientes para el login con sus respectivos mensajes de error @CarlosDaniel661 @Monagodino @maria1531

**Comment by CarlosDaniel661** [comment]
Testeado - Aprobado
