### ISSUE TITLE
Añadir swagger para documentar backend node

### ISSUE THREAD

**Issue by JackDev21** [igrowker/i004-reffindr-back-nodejs#53]

**Comment by CarlosDaniel661** [comment]
Por favor, detallar concretamente cuales son las acciones necesarias a revisar, a modo de adaptar los test necesarios

**Comment by gonzalorosofsky** [comment]
> Por favor, detallar concretamente cuales son las acciones necesarias a revisar, a modo de adaptar los test necesarios

En este caso seria verificar que el swagger es accesible y funcional para realizar pruebas.

**Comment by CarlosDaniel661** [comment]
Testeado - Aprobado
